name: Generate and Update Economic Calendar

on:
  # This runs the script every day at 05:00 UTC (around 10:30 AM IST)
  # You can change the '0 5' to your preferred hour and minute in UTC.
  schedule:
    - cron: '0 5 * * *'
  # This line allows you to run it manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
    # 1. Checks-out your repository so the job can access your script
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2. Sets up the Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. Installs the necessary libraries
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests ics

    # 4. Runs your Python script to generate the .ics file
    - name: Run Python Script
      run: python create_final_calendar.py

    # 5. Commits the newly generated .ics file back to the repository
    - name: Commit and Push Updated Calendar
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add --all
        # The following command only commits if there are actual changes
        git diff --staged --quiet || git commit -m "Update economic events calendar"
        git push
